sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        nRlqs7kI+nkHufSRfu9T56+wTKGd6ilxA4a5LbP6k8h3RZ8eWblsrZp0CpMRCEYi/ZjKkLmZyKCD/VKjqgxCHYTOxxgy5YJ5ZwIFsFBp0K4rx8NkxFoaOeWhW/WK4C5fsrgoBtg9e5ZA1jBxR97kLW1430sLNjzVn2RqJLDTyzOz/qEqTD1DDsxgFBNupnoxs1btkp3VDNciIpJO7bxmTi1w/+SDaz1eYLFhDxodciINXAj1LDi78/h5YGv1RJLRtc0i42R471NCJUTp9DG7zZl5Ysu4pG36bZVrmIt14//zUraD3BqY2y3nSPq6EVFeWuQQKg+8Wi5cYypzTJz1NuKXQPC4xFPn7csj7k1u/L6+7aVGTL9eBmktAXW3d/H9PizzIbBQQdVaukd4jDSrG8UM9fX3dZhxVCNWPCDNx+pHgdPo5VOI9xgu42tSMjUyKQREotS+qABWiHFJtcLfCDqS6ZkCa75Fl18K5VBTpbs7/JZfaoZ0r2hAQwlM+xoA9QQZzH0jtAWH+DF0Thpl7Wmr1Lg7j8jxYyAZ4gs+R8Z0o3LIQBUKs4d66tJuHlTr2hHwDJof4UjrHPLl2XYRGDbXtuu85GdnOCXbPuN2OloRA5xHd9OlH2mVUTtEmq/CKOh9xqMnywF1iPR7Y8ulQ4PirTPOtVyw7Bd/Mp85u4Q=
    - secure: >-
        kGKqoAT5yvXNbixOQ81NMOmwxtEDfSXbhF3rwwydtwKy7r3CxfE/WxaMkC9Htd5LDKb9DrCf+HsJJGScdGd9honZ33ipXrydaE6r0j6Lpg7lzRV0J2LVs8XJhjn0ybOe+wRVSTpKh50qlq0CfT0Fd/BoAeUGBEnNLNOk5pTTrXCKH6X8qkgdguFmPlhPjCrJWjxucsReNyQgtXjW3aI27Mm6QQWqIZNcHYs0FlqZ3PYyDX2FOMBILpRhhZmhVcSTDvDg3UgrwzRHP3agWksCrgrXcN3Y5EY9ppHJo+7DVHXVf5nb3KRmpWvxghtYFdYQHLCx59N6RjwHdTHKARis40cihtu0p6WYycUFJ/lDG8IkAQMkDWbt03RQIYPuJHz4r70YojRhRwGlmwDVD+FIW0byY5B1sCqmx1ezyRoVah6lcXxy0rnpcjwUY/5pO3/obx9JROps+4GaIzPJGpsatjXgbHS21kXVxBsmc2Q3jZCp6PqQ6le6WbKEN8McPnaFwXJTqc2FlTDpWfNWqV15XveyxWZ4oElLpRrtg0jtUs8bp0CALXDmxTA1lDD9zE2cX+5nP/1FTJNBS+fY9z15NI5XpiWsygUDoyvBQlM0UVFEFlfe53ErS54voyc/ofHihzZLh+hvC5QAX8qotuMkZX8WnwveNvjbzfyVskCjCx8=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
